name: memset test ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install prerequisites
      run: sudo apt-get install -y wget autoconf automake autotools-dev curl python3 python3-pip python3-tomli libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev libslirp-dev
    - name: download riscv toolchain
      run: wget https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2024.03.01/riscv64-elf-ubuntu-22.04-gcc-nightly-2024.03.01-nightly.tar.gz
    - name: install riscv toolchain
      run: |
        mkdir -p /home/runner/opt/cross
        tar -xvf riscv64-elf-ubuntu-22.04-gcc-nightly-2024.03.01-nightly.tar.gz -C /home/runner/opt/cross --strip-components=1

    - name: riscv simulator spike
      run: |
        sudo apt install build-essential device-tree-compiler libboost-regex-dev libboost-system-dev
        git clone https://github.com/riscv-software-src/riscv-isa-sim.git spike
        pushd spike
        mkdir build && cd build && ../configure --prefix=/home/runner/opt/cross
        make -j$(nproc)
        sudo make install
        popd

    - name: download and install riscv pk
      run: |
        git clone https://github.com/riscv-software-src/riscv-pk
        pushd riscv-pk
        export PATH=$PATH:/home/runner/opt/cross/bin
        mkdir build && cd build && ../configure --prefix=/home/runner/opt/cross --host=riscv64-unknown-elf
        make -j$(nproc)
        sudo make install
        popd

    - name: compile test harness
      run: make exe

    - name: run test
      run: make run
